import fs from 'node:fs';
const games = JSON.parse(fs.readFileSync(new URL('./dist/catalog.json', import.meta.url), 'utf8').replace(/^\uFEFF/, ''));
const esc = s => String(s || '').replace(/[&<>"']/g, c => ({'&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;'}[c]));
const local = games.filter(g => g.local);
const linked = games.filter(g => !g.local);
const list = entries => entries.map(g => `<li><a href="./#game=${encodeURIComponent(g.id)}">${esc(g.title)}</a><span>${esc(g.provider)}${g.developer ? ' · ' + esc(g.developer) : ''} · <a href="${esc(g.sourceUrl)}" target="_blank" rel="noopener noreferrer">Source ↗</a></span></li>`).join('');
fs.writeFileSync(new URL('./dist/credits.html', import.meta.url), `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Game credits — Afterhours</title><link rel="stylesheet" href="styles.css?v=play-2"><style>body{max-width:1050px;margin:auto;padding:40px 24px}h1{margin:35px 0 20px}h2{font-family:var(--display);margin-top:35px}p{color:#b3bbc8}a{color:var(--lime)}.credits-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px}.credit{padding:20px;border:1px solid var(--line);border-radius:9px;background:var(--panel)}.credit h3{margin:0 0 8px}.credit p{font-size:14px;margin:7px 0}.credits-list{columns:3;column-gap:30px;padding:0;list-style:none}.credits-list li{break-inside:avoid;padding:7px 0;font-size:14px}.credits-list span{display:block;font-size:12px;color:var(--muted)}@media(max-width:650px){.credits-list{columns:2}}@media(max-width:420px){.credits-list{columns:1}}</style></head>
<body><a href="./">← Back to the arcade</a><h1>Behind the games</h1><p>Games are made by their respective developers. Publisher names, game titles, artwork, and other assets belong to their owners.</p>
<h2>Included with this site</h2><p>These ${local.length} open-source games are included with their source, license notices, and attribution.</p><div class="credits-grid">${local.map(g => `<article class="credit"><h3>${esc(g.title)}</h3><p>${esc(g.authors)}</p><p>${esc(g.license)}</p><p><a href="${esc(g.sourceUrl)}" target="_blank" rel="noopener noreferrer">Original source ↗</a></p><a href="games/${esc(g.id)}/ARCADE-NOTICES.md">Licenses & modifications</a></article>`).join('')}</div>
<h2>More games</h2><p>These ${linked.length} games are maintained by their developers, publishers, or the repositories linked below.</p><ul class="credits-list">${list(linked)}</ul>
<h2>Artwork and fonts</h2><p>Snow Rider artwork comes from GameBiz and Slope artwork from Y8. Other game artwork comes from its game or publisher listing. The SVG card illustrations are original artwork made for this arcade; they are not official game art or screenshots.</p><p>DM Sans and Space Grotesk are served from this site under the SIL Open Font License: <a href="assets/fonts/dm-sans-OFL.txt">DM Sans license</a> · <a href="assets/fonts/space-grotesk-OFL.txt">Space Grotesk license</a>.</p>
<h2>Your favorites</h2><p>Favorites and recently played games are saved in this browser. Games may store their own progress, preferences, and cookies. Clearing browser storage clears this arcade's saved list.</p><p><a href="./">← Find your next game</a></p></body></html>`);
